spring:
  security:
    saml2:
      relyingparty:
        registration:
          okta:
            signing:
              credentials:
                - private-key-location: classpath:certs/local.key
                  certificate-location: classpath:certs/local.crt
            singlelogout:
              url: https://dev-56617222.okta.com/app/dev-56617222_springbootsaml_1/exk8b5jr6vYQqVXp45d7/slo/saml
              binding: post
              response-url: "{baseUrl}/logout/saml2/slo"
            assertingparty:
              metadata-uri: classpath:metadata/metadata-idp-okta.xml
              singlesignon:
                url: https://dev-56617222.okta.com/app/dev-56617222_springbootsaml_1/sso/saml
                binding: post
              verification:
                signature:
                  enabled: false  # Disable signature validation for Okta

          authgateway:
            signing:
              credentials:
                - private-key-location: classpath:certs/sp-private-key.pem
                  certificate-location: classpath:certs/idp-public-key.crt
            singlelogout:
              url: http://localhost:9090/api/v1/saml/logout
              binding: post
              response-url: "{baseUrl}/logout/saml2/slo"
            assertingparty:
              metadata-uri: classpath:metadata/metadata-idp-authgateway.xml
              singlesignon:
                url: http://localhost:9090/api/v1/saml/auth/login/7fdc623d-c142-467f-85ce-e843580407a9
                binding: post
              verification:
                signature:
                  enabled: false  # Disable signature validation for AuthGateway


logging:
  level:
    org.springframework.security.saml2: DEBUG
    org.springframework.security: DEBUG
    com.authgateway: DEBUG
