spring:
  security:
    saml2:
      relyingparty:
        registration:
          okta:
            signing:
              credentials:
                - private-key-location: classpath:local.key
                  certificate-location: classpath:local.crt
            singlelogout:
              url: https://dev-56617222.okta.com/app/dev-56617222_springbootsaml_1/exk8b5jr6vYQqVXp45d7/slo/saml
              binding: post
              response-url: "{baseUrl}/logout/saml2/slo"
            assertingparty:
              metadata-uri: classpath:metadata/metadata-idp-okta.xml
              singlesignon:
                url: https://dev-56617222.okta.com/app/dev-56617222_springbootsaml_1/sso/saml
                binding: post

          authgateway:
            signing:
              credentials:
                - private-key-location: classpath:authgateway.key
                  certificate-location: classpath:authgateway.crt
            singlelogout:
              url: https://authgateway.example.com/sso/saml/logout
              binding: post
              response-url: "{baseUrl}/logout/saml2/slo"
            assertingparty:
              metadata-uri: classpath:metadata/metadata-idp-authgateway.xml
              singlesignon:
                url: https://authgateway.example.com/sso/saml
                binding: post
